server:
  port: 8083

info:
  app:
    name: Auth-Server
    description: Servidor de Autenticação

management:
  endpoint:
    beans:
      enabled: true

  
spring:
  application:
    name: auth-center

eureka:
  instance:
    leaseRenewalIntervalInSeconds: 5
    leaseExpirationDurationInSeconds: 2
  client:
    serviceUrl:
      defaultZone: http://localhost:8761/eureka/
      healthcheck:
      enabled: true
      lease:
      duration: 5
      
shuaicj.security.jwt.secret: otherpeopledontknowit
