server:
  port: 8080

info:
  app:
    name: API Gateway Zull
    description: API Gateway

management:
  endpoint:
    beans:
      enabled: true
  endpoints:  
    web:
      exposure:
        include: "*" 
      
spring:
  application:
    name: api-gateway
  datasource:
    driverClassName: org.postgresql.Driver
    url: jdbc:postgresql://localhost:5432/controle-acesso
    username: postgres
    password: root
    
eureka:
  client:
    serviceUrl:
      defaultZone: http://localhost:8761/eureka/
      healthcheck:
      enabled: true

zuul:
  ignoredServices: '*'
  sensitiveHeaders: Cookie,Set-Cookie
  ignoreSecurityHeaders: false
  routes:
    auth-center:
      path: /login/**
      url: http://127.0.0.1:8083/
      stripPrefix: false
    modulo-controle-coleta-definicao-cargas:
      path: /modulo-coleta/**
      url: http://127.0.0.1:8081/
      service-id: modulo-coleta
      stripPrefix: true
    modulo-controle-frete:
      path: /modulo-frete/**
      url: http://127.0.0.1:8082/
      service-id: modulo-frete
      stripPrefix: true

shuaicj.security.jwt.secret: otherpeopledontknowit
